### ISSUE TITLE
SyntaxError: Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by vscheuber** [rockcarver/frodo#200]
frodo -v
/snapshot/frodo/dist/src/cli/idp/idp.js:16
const _dirname = _path.default.dirname((0, _url.fileURLToPath)(import.meta.url));
                                                                      ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at Object.compileFunction (node:vm:354:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._compile (pkg/prelude/bootstrap.js:1937:32)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by vscheuber** [comment]
Still seeing errors:

frodo journey list dmdc
/snapshot/frodo/dist/node_modules/commander/lib/command.js:1028
        throw new Error(executableMissing);
        ^

Error: 'journey-list' does not exist
 - if 'list' is not meant to be an executable command, remove description parameter from '.command()' and use '.description()' instead
 - if the default executable name is not suitable, use the executableFile option to supply a custom name or path
 - searched for local subcommand relative to directory '/snapshot/frodo/dist/src/cli/journey'
    at ChildProcess.<anonymous> (/snapshot/frodo/dist/node_modules/commander/lib/command.js:1028:15)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:64:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1984:13)
    at node:internal/main/run_main_module:17:47

Node.js v18.1.0
